<?php

namespace StockBundle\Repository;

/**
 * produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitRepository extends \Doctrine\ORM\EntityRepository
{

    public function  findEntitiesByString($str){
        $query=$this->getEntityManager()->createQuery("SELECT c FROM StockBundle:produit c where c.nomProduit LIKE :str")->setParameter('str', '%'.$str.'%');
        return $query->getResult();
    }
}
