<?php

namespace FrontOfficeBundle\Repository;

/**
 * paiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paiementRepository extends \Doctrine\ORM\EntityRepository
{
}
