<?php

namespace FrontOfficeBundle\Repository;

/**
 * paiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paiementRepository extends \Doctrine\ORM\EntityRepository
{
    public function  findpaimentbydetail($id){
        $query=$this->getEntityManager()->createQuery("SELECT c FROM FrontOfficeBundle:detail_commande c where c.Commande ='$id' ");
        return $query->getResult();
}
